library(tidyverse)
root="https://raw.githubusercontent.com/nangokosu/math-245-project/main/data/"
parliament_data <- read_csv(paste0(root,"parliament.csv"))
happy_data <-read_csv(paste0(root,"hapiscore_whr.csv"))
unemployment_data<-read_csv(paste0(root,"aged_15plus_employment_rate_percent.csv"))
right_data <-read_csv(paste0(root,"right.csv"))
sanitation_data <- read_csv(paste0(root,"sanitation.csv"))
hdi_data <-read_csv(paste0(root,"hdiindex.csv"))
edu_data <- read_csv(paste0(root,"edu.csv"))
internet_data <- read_csv(paste0(root,"internetusers.csv"))
sdi_data <- read_csv(paste0(root,"sdi.csv"))
forest_data <- read_csv(paste0(root,"forestcoverage.csv"))
militaryexpenditure_data <- read_csv(paste0(root,"militaryexpenditure.csv"))
mortality_data <- read_csv(paste0(root,"mortality.csv"))
water_data <- read_csv(paste0(root,"wateraccess.csv"))
broadband_data <- read_csv(paste0(root,"broadband.csv"))
agriculture_data <- read_csv(paste0(root,"agriculture.csv"))
debt_data <- read_csv(paste0(root,"debt.csv"))
gdp_data <- read_csv(paste0(root,"gdppercapita.csv"))
food_data <- read_csv(paste0(root,"foodinsecurity.csv"))

parliament_tall <-gather(parliament_data, key="year", value="parliament",-country)
parliament_tall <- mutate(parliament_tall, year=as.numeric(year))
happy_tall <-gather(happy_data, key="year",value="happy", -country)
happy_tall <- mutate(happy_tall, year=as.numeric(year))
unemployment_tall <- gather(unemployment_data, key="year",value="unemployment", -country)
unemployment_tall <- mutate(unemployment_tall, year=as.numeric(year))
right_tall <-gather(right_data, key="year", value="rights",-country)
right_tall <- mutate(right_tall, year=as.numeric(year))
sanitation_tall <-gather(sanitation_data, key="year", value="sanitation",-country)
sanitation_tall <- mutate(sanitation_tall, year=as.numeric(year))
edu_tall <- gather(edu_data, key="year", value="education", -country)
edu_tall <- mutate(edu_tall, year=as.numeric(year))
sdi_tall <- gather(sdi_data, key="year", value="sustainability", -country)
sdi_tall <- mutate(sdi_tall, year=as.numeric(year))
internet_tall <- gather(internet_data, key="year", value="internet", -country)
internet_tall <- mutate(internet_tall, year=as.numeric(year))
hdi_tall <- gather(hdi_data, key="year", value="hdi", -country)
hdi_tall <- mutate(hdi_tall, year=as.numeric(year))
forest_tall <- gather(forest_data, key="year", value="forest", -country)
forest_tall <- mutate(forest_tall, year=as.numeric(year))
militaryexpenditure_tall <- gather(militaryexpenditure_data, key="year", value="militaryexpenditure", -country)
militaryexpenditure_tall <- mutate(militaryexpenditure_tall, year=as.numeric(year))
mortality_tall <- gather(mortality_data, key="year", value="mortality", -country)
mortality_tall <- mutate(mortality_tall, year=as.numeric(year))
water_tall <- gather(water_data, key="year", value="water", -country)
water_tall <- mutate(water_tall, year=as.numeric(year))
broadband_tall <- gather(broadband_data, key="year", value="broadband", -country)
broadband_tall <- mutate(broadband_tall, year=as.numeric(year))
agriculture_tall <- gather(agriculture_data, key="year", value="agriculture", -country)
agriculture_tall <- mutate(agriculture_tall, year=as.numeric(year))
debt_tall <- gather(debt_data, key="year", value="debt", -country)
debt_tall <- mutate(debt_tall, year=as.numeric(year))
gdp_tall <- gather(gdp_data, key="year", value="GDPpercapita_growth", -country)
gdp_tall <- mutate(gdp_tall, year=as.numeric(year))
food_tall <- gather(food_data, key="year", value="foodinsecurity", -country)
food_tall <- mutate(food_tall, year=as.numeric(year))


full_data <- full_join(happy_tall,parliament_tall,by=c("country","year"))
full_data <- full_join(full_data,unemployment_tall,by=c("country","year"))
full_data <- full_join(full_data,right_tall,by=c("country","year"))
full_data <- full_join(full_data,sanitation_tall,by=c("country","year"))
full_data <- full_join(full_data,edu_tall,by=c("country","year"))
full_data <- full_join(full_data,internet_tall,by=c("country","year"))
full_data <- full_join(full_data,sdi_tall,by=c("country","year"))
full_data <- full_join(full_data,hdi_tall,by=c("country","year"))
full_data <- full_join(full_data,forest_tall,by=c("country","year"))
full_data <- full_join(full_data,militaryexpenditure_tall,by=c("country","year"))
full_data <- full_join(full_data,mortality_tall,by=c("country","year"))
full_data <- full_join(full_data,water_tall,by=c("country","year"))
full_data <- full_join(full_data,broadband_tall,by=c("country","year"))
full_data <- full_join(full_data,agriculture_tall,by=c("country","year"))
full_data <- full_join(full_data,debt_tall,by=c("country","year"))
full_data <- full_join(full_data,gdp_tall,by=c("country","year"))
full_data <- full_join(full_data,food_tall,by=c("country","year"))

full_data2 <- filter(full_data, year==2016)

full_data2$unemployment <- as.numeric(as.character(full_data2$unemployment))*100
full_data2$rights <- as.numeric(as.character(full_data2$rights))*100
full_data2$sanitation <- as.numeric(as.character(full_data2$sanitation))*100
full_data2$parliament <- as.numeric(as.character(full_data2$parliament))*100
full_data2$happy <- as.numeric(as.character(full_data2$happy))*100
full_data2$internet <- as.numeric(full_data2$internet)

#The data we are using
View(full_data2)

#Convert NAs in response variable to 0
full_data2 <- mutate_if(full_data2, is.numeric, ~replace(., is.na(.), 0))

#Remove all missing values
full_data3 <- subset(full_data2, !is.na(full_data2$parliament))
full_data3 <- subset(full_data3, !is.na(full_data3$happy))
full_data3 <- subset(full_data3, !is.na(full_data3$unemployment))
full_data3 <- subset(full_data3, !is.na(full_data3$gini))
full_data3 <- subset(full_data3, !is.na(full_data3$sanitation))
full_data3 <- subset(full_data3, !is.na(full_data3$rights))
full_data3 <- subset(full_data3, !is.na(full_data3$education))
full_data3 <- subset(full_data3, !is.na(full_data3$internet))
full_data3 <- subset(full_data3, !is.na(full_data3$sustainability))
full_data3 <- subset(full_data3, !is.na(full_data3$hdi))
full_data3 <- subset(full_data3, !is.na(full_data3$forest))
full_data3 <- subset(full_data3, !is.na(full_data3$militaryexpenditure))
full_data3 <- subset(full_data3, !is.na(full_data3$mortality))
full_data3 <- subset(full_data3, !is.na(full_data3$water))
full_data3 <- subset(full_data3, !is.na(full_data3$broadband))
full_data3 <- subset(full_data3, !is.na(full_data3$agriculture))
full_data3 <- subset(full_data3, !is.na(full_data3$debt))
full_data3 <- subset(full_data3, !is.na(full_data3$GDPpercapita_growth))
full_data3 <- subset(full_data3, !is.na(full_data3$foodinsecurity))
